# Generated by Django 6.0.4 on 2026-05-23 23:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        ('mutuelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(db_index=True, default='XOF', max_length=3)),
                ('provider', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('wave', 'Wave'), ('moov_money', 'Moov Money'), ('cash', 'Espèces'), ('bank', 'Banque')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('initiated', 'Initialisé'), ('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('reversed', 'Annulé')], db_index=True, default='initiated', max_length=24)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('purpose', models.CharField(db_index=True, max_length=80)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='memberships.member')),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
            ],
            options={
                'indexes': [models.Index(fields=['mutuelle', 'provider', 'status'], name='payments_pa_mutuell_e56c44_idx')],
            },
        ),
    ]
