# Generated by Django 6.0.4 on 2026-05-23 23:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mutuelles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_members', models.PositiveIntegerField(default=500)),
                ('max_storage_mb', models.PositiveIntegerField(default=1024)),
                ('max_monthly_ai_calls', models.PositiveIntegerField(default=1000)),
                ('max_mandataires', models.PositiveIntegerField(default=25)),
                ('current_storage_mb', models.PositiveIntegerField(default=0)),
                ('current_monthly_ai_calls', models.PositiveIntegerField(default=0)),
                ('reset_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mutuelle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='mutuelles.mutuelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('resource_type', models.CharField(db_index=True, max_length=120)),
                ('resource_id', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mutuelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mutuelles.mutuelle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mutuelle', 'action', 'created_at'], name='core_auditt_mutuell_b7a0f3_idx'), models.Index(fields=['resource_type', 'resource_id'], name='core_auditt_resourc_88076d_idx')],
            },
        ),
    ]
