# Generated by Django 6.0.4 on 2026-05-23 23:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mutuelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_type', models.CharField(db_index=True, max_length=80)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI compatible'), ('ollama', 'Ollama local')], db_index=True, default='ollama', max_length=24)),
                ('prompt', models.TextField()),
                ('result', models.JSONField(blank=True, default=dict)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('related_object_type', models.CharField(blank=True, max_length=120)),
                ('related_object_id', models.CharField(blank=True, max_length=120)),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
            ],
            options={
                'indexes': [models.Index(fields=['mutuelle', 'analysis_type', 'created_at'], name='ai_engine_a_mutuell_100e8c_idx')],
            },
        ),
    ]
