# Generated by Django 6.0.4 on 2026-05-23 23:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        ('mutuelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('frequency', models.CharField(choices=[('monthly', 'Mensuelle'), ('yearly', 'Annuelle'), ('exceptional', 'Exceptionnelle')], db_index=True, max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(db_index=True, default='XOF', max_length=3)),
                ('due_date', models.DateField(db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('due', 'Due'), ('partial', 'Partielle'), ('paid', 'Payée'), ('overdue', 'En retard')], db_index=True, default='due', max_length=24)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=80)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='memberships.member')),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contributions.contributionplan')),
            ],
        ),
        migrations.AddIndex(
            model_name='contributionplan',
            index=models.Index(fields=['mutuelle', 'created_at'], name='contributio_mutuell_7d2a30_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['mutuelle', 'status', 'due_date'], name='contributio_mutuell_158df0_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['member', 'status'], name='contributio_member__106d10_idx'),
        ),
    ]
