# Generated by Django 6.0.4 on 2026-05-25 12:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        ('mutuelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(db_index=True, default='XOF', max_length=3)),
                ('claim_type', models.CharField(choices=[('illness', 'Maladie'), ('death', 'Décès'), ('accident', 'Accident'), ('maternity', 'Maternité'), ('marriage', 'Mariage'), ('disaster', 'Catastrophe'), ('education', 'Aide scolaire')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Demandée'), ('review', 'Analyse'), ('approved', 'Approuvée'), ('paid', 'Payée'), ('closed', 'Clôturée'), ('rejected', 'Rejetée')], db_index=True, default='draft', max_length=24)),
                ('beneficiary_name', models.CharField(blank=True, max_length=180)),
                ('incident_date', models.DateField(blank=True, db_index=True, null=True)),
                ('description', models.TextField()),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('decision_notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistance_claims', to='memberships.member')),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(db_index=True, max_length=80)),
                ('file', models.FileField(upload_to='claims/documents/')),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('ocr_payload', models.JSONField(blank=True, default=dict)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims.assistanceclaim')),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
            ],
        ),
        migrations.AddIndex(
            model_name='assistanceclaim',
            index=models.Index(fields=['mutuelle', 'status', 'claim_type'], name='claims_assi_mutuell_f8778e_idx'),
        ),
        migrations.AddIndex(
            model_name='assistanceclaim',
            index=models.Index(fields=['member', 'status'], name='claims_assi_member__fef182_idx'),
        ),
        migrations.AddIndex(
            model_name='claimdocument',
            index=models.Index(fields=['mutuelle', 'document_type', 'verified'], name='claims_clai_mutuell_c3cd92_idx'),
        ),
    ]
