from django.urls import path
from django.contrib.auth.views import LogoutView

from dashboard.views import (
    ai_copilot_center,
    branding_center,
    claims_center,
    console_dashboard,
    advance_assistance_claim,
    advance_mortgage_application,
    create_ai_decision_note,
    create_assistance_claim,
    create_assembly,
    create_contribution,
    create_contribution_plan,
    create_financial_profile,
    create_financing_scenario_view,
    contribution_receipt,
    create_member,
    create_mortgage_application,
    create_mutuelle,
    create_payment,
    create_project,
    create_reservation,
    create_resolution,
    create_simulation,
    documents_center,
    field_offline_center,
    finance_center,
    financing_center,
    finance_export_csv,
    governance_center,
    landing_page,
    members_center,
    notifications_center,
    mutuelle_detail,
    mutuelle_report,
    mutuelle_report_pdf,
    mutuelles_list,
    projects_center,
    process_property_document,
    profile_center,
    public_mutuelle_signup,
    reports_center,
    request_mfa_challenge,
    security_center,
    simulations_center,
    create_notification,
    simulate_payment_success,
    SecureLoginView,
    upload_property_document,
    update_mutuelle_branding,
    verify_mfa_challenge,
)

urlpatterns = [
    path("", landing_page, name="landing-page"),
    path("creer-une-mutuelle/", public_mutuelle_signup, name="public-mutuelle-signup"),
    path("connexion/", SecureLoginView.as_view(), name="login"),
    path("deconnexion/", LogoutView.as_view(), name="logout"),
    path("console/", console_dashboard, name="dashboard-home"),
    path("console/mutuelles/", mutuelles_list, name="mutuelles-list"),
    path("console/mutuelles/<uuid:mutuelle_id>/", mutuelle_detail, name="mutuelle-detail"),
    path("console/projets/", projects_center, name="projects-center"),
    path("console/membres/", members_center, name="members-center"),
    path("console/simulations/", simulations_center, name="simulations-center"),
    path("console/documents/", documents_center, name="documents-center"),
    path("console/notifications/", notifications_center, name="notifications-center"),
    path("console/terrain-offline/", field_offline_center, name="field-offline-center"),
    path("console/ia/", ai_copilot_center, name="ai-copilot-center"),
    path("console/gouvernance/", governance_center, name="governance-center"),
    path("console/branding/", branding_center, name="branding-center"),
    path("console/securite/", security_center, name="security-center"),
    path("console/profil/", profile_center, name="profile-center"),
    path("console/rapports/", reports_center, name="reports-center"),
    path("console/finances/", finance_center, name="finance-center"),
    path("console/financements/", financing_center, name="financing-center"),
    path("console/prestations/", claims_center, name="claims-center"),
    path("console/finances/export.csv", finance_export_csv, name="finance-export-csv"),
    path("console/mutuelles/nouvelle/", create_mutuelle, name="create-mutuelle"),
    path("console/membres/nouveau/", create_member, name="create-member"),
    path("console/profils-financiers/nouveau/", create_financial_profile, name="create-financial-profile"),
    path("console/projets/nouveau/", create_project, name="create-project"),
    path("console/simulations/nouvelle/", create_simulation, name="create-simulation"),
    path("console/financements/scenarios/nouveau/", create_financing_scenario_view, name="create-financing-scenario"),
    path("console/financements/dossiers/nouveau/", create_mortgage_application, name="create-mortgage-application"),
    path("console/financements/dossiers/<uuid:application_id>/avancer/", advance_mortgage_application, name="advance-mortgage-application"),
    path("console/prestations/nouvelle/", create_assistance_claim, name="create-assistance-claim"),
    path("console/prestations/<uuid:claim_id>/avancer/", advance_assistance_claim, name="advance-assistance-claim"),
    path("console/reservations/nouvelle/", create_reservation, name="create-reservation"),
    path("console/finances/plans/nouveau/", create_contribution_plan, name="create-contribution-plan"),
    path("console/finances/cotisations/nouvelle/", create_contribution, name="create-contribution"),
    path("console/finances/paiements/nouveau/", create_payment, name="create-payment"),
    path("console/finances/paiements/<uuid:payment_id>/simuler-succes/", simulate_payment_success, name="simulate-payment-success"),
    path("console/notifications/nouvelle/", create_notification, name="create-notification"),
    path("console/ia/note-decision/", create_ai_decision_note, name="create-ai-decision-note"),
    path("console/gouvernance/assemblees/nouvelle/", create_assembly, name="create-assembly"),
    path("console/gouvernance/resolutions/nouvelle/", create_resolution, name="create-resolution"),
    path("console/securite/otp/generer/", request_mfa_challenge, name="request-mfa-challenge"),
    path("console/securite/otp/verifier/", verify_mfa_challenge, name="verify-mfa-challenge"),
    path("console/documents/importer/", upload_property_document, name="upload-property-document"),
    path("console/documents/<uuid:document_id>/ocr/", process_property_document, name="process-property-document"),
    path("console/mutuelles/<uuid:mutuelle_id>/rapport/", mutuelle_report, name="mutuelle-report"),
    path("console/mutuelles/<uuid:mutuelle_id>/rapport.pdf", mutuelle_report_pdf, name="mutuelle-report-pdf"),
    path("console/mutuelles/<uuid:mutuelle_id>/branding/", update_mutuelle_branding, name="update-mutuelle-branding"),
    path("console/cotisations/<uuid:contribution_id>/recu.pdf", contribution_receipt, name="contribution-receipt"),
]
