# Generated by Django 6.0.4 on 2026-05-23 23:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mutuelles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_code', models.CharField(db_index=True, max_length=40)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('qr_token', models.CharField(db_index=True, max_length=120, unique=True)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Actif'), ('delinquent', 'En retard'), ('suspended', 'Suspendu')], db_index=True, default='prospect', max_length=24)),
                ('joined_at', models.DateField(blank=True, db_index=True, null=True)),
                ('location', models.JSONField(blank=True, default=dict, null=True)),
                ('kyc_validated', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(db_index=True, max_length=80)),
                ('file', models.FileField(upload_to='members/kyc/')),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('ocr_payload', models.JSONField(blank=True, default=dict)),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='memberships.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=180)),
                ('relationship', models.CharField(max_length=60)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('kyc_document', models.FileField(blank=True, null=True, upload_to='beneficiaries/kyc/')),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='memberships.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['mutuelle', 'status'], name='memberships_mutuell_f4a26b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['mutuelle', 'phone'], name='memberships_mutuell_05c8bc_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['mutuelle', 'kyc_validated'], name='memberships_mutuell_62f6f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('mutuelle', 'member_code')},
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['mutuelle', 'created_at'], name='memberships_mutuell_0dec77_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['mutuelle', 'created_at'], name='memberships_mutuell_0dafa4_idx'),
        ),
    ]
