# Generated by Django 6.0.5 on 2026-05-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_member_profile_and_bank'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bank',
            new_name='memberships_country_95da46_idx',
            old_name='memberships_bank_country_active_idx',
        ),
        migrations.RenameIndex(
            model_name='member',
            new_name='memberships_mutuell_b2852c_idx',
            old_name='memberships_m_marital_idx',
        ),
        migrations.RenameIndex(
            model_name='member',
            new_name='memberships_mutuell_8dc787_idx',
            old_name='memberships_m_bank_idx',
        ),
    ]
