# Generated by Django 6.0.4 on 2026-05-24 23:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        ('mutuelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAssembly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=180)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('online_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifiée'), ('live', 'En cours'), ('closed', 'Clôturée')], db_index=True, default='draft', max_length=24)),
                ('quorum_required', models.PositiveSmallIntegerField(default=50)),
                ('minutes', models.TextField(blank=True)),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=180)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Vote ouvert'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], db_index=True, default='draft', max_length=24)),
                ('approval_threshold', models.PositiveSmallIntegerField(default=50)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='governance.generalassembly')),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.CharField(choices=[('yes', 'Pour'), ('no', 'Contre'), ('abstain', 'Abstention')], db_index=True, max_length=16)),
                ('signed_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_votes', to='memberships.member')),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='governance.resolution')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature_type', models.CharField(choices=[('attendance', 'Présence AG'), ('resolution', 'Résolution'), ('contract', 'Contrat')], db_index=True, max_length=24)),
                ('related_object_type', models.CharField(blank=True, max_length=120)),
                ('related_object_id', models.CharField(blank=True, max_length=120)),
                ('signature_hash', models.CharField(db_index=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=180)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_signatures', to='memberships.member')),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
            ],
            options={
                'indexes': [models.Index(fields=['mutuelle', 'signature_type', 'created_at'], name='governance__mutuell_c90585_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='generalassembly',
            index=models.Index(fields=['mutuelle', 'status', 'scheduled_at'], name='governance__mutuell_8e4afe_idx'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['mutuelle', 'status'], name='governance__mutuell_6d46b8_idx'),
        ),
        migrations.AddIndex(
            model_name='resolutionvote',
            index=models.Index(fields=['mutuelle', 'choice', 'voted_at'], name='governance__mutuell_69513a_idx'),
        ),
        migrations.AddConstraint(
            model_name='resolutionvote',
            constraint=models.UniqueConstraint(fields=('resolution', 'member'), name='unique_resolution_member_vote'),
        ),
    ]
