# Generated by Django 6.0.4 on 2026-05-23 23:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mutuelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('main', 'Caisse principale'), ('agency', 'Caisse agence'), ('bank', 'Compte bancaire'), ('mobile_money', 'Mobile Money')], db_index=True, max_length=32)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(db_index=True, default='XOF', max_length=3)),
                ('direction', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], db_index=True, max_length=12)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='treasury.cashaccount')),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='mutuelles.mutuelle')),
            ],
        ),
        migrations.AddIndex(
            model_name='cashaccount',
            index=models.Index(fields=['mutuelle', 'created_at'], name='treasury_ca_mutuell_55b44d_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['mutuelle', 'direction', 'occurred_at'], name='treasury_le_mutuell_a2fcd6_idx'),
        ),
    ]
