# Generated by Django 6.0.4 on 2026-05-23 23:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutuelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=180)),
                ('country', models.CharField(db_index=True, default='CI', max_length=2)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En validation'), ('active', 'Active'), ('suspended', 'Suspendue')], db_index=True, default='draft', max_length=24)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mutuelles/logos/')),
                ('primary_color', models.CharField(default='#0f766e', max_length=16)),
                ('accent_color', models.CharField(default='#f59e0b', max_length=16)),
                ('subscription_plan', models.CharField(db_index=True, default='starter', max_length=60)),
                ('custom_domain', models.CharField(blank=True, db_index=True, max_length=180)),
                ('headquarters_location', models.JSONField(blank=True, default=dict, null=True)),
                ('business_rules', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'status'], name='mutuelles_m_country_f02b2a_idx'), models.Index(fields=['subscription_plan', 'status'], name='mutuelles_m_subscri_f56ced_idx')],
            },
        ),
        migrations.CreateModel(
            name='MutuelleMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(db_index=True, max_length=32)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('mutuelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_memberships', to='mutuelles.mutuelle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutuelle_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['mutuelle', 'role', 'active'], name='mutuelles_m_mutuell_5329a4_idx')],
                'unique_together': {('mutuelle', 'user')},
            },
        ),
    ]
