# Generated by Django 6.0.5 on 2026-05-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutuelles', '0003_mutuelle_onboarding_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mutuelle',
            new_name='mutuelles_m_real_es_fa5013_idx',
            old_name='mutuelles_m_re_obj_status_idx',
        ),
        migrations.RenameIndex(
            model_name='mutuelle',
            new_name='mutuelles_m_organiz_eb557f_idx',
            old_name='mutuelles_m_org_status_idx',
        ),
        migrations.AlterField(
            model_name='mutuelle',
            name='legal_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='mutuelle',
            name='name',
            field=models.CharField(db_index=True, max_length=180, verbose_name='Nom de la mutuelle'),
        ),
    ]
